### ISSUE TITLE
Add all projects to the project list

### ISSUE THREAD

**Issue by m-linner-ericsson** [eiffel-community/community#127]
### Description
Not all repositories part of the project lists

### Motivation
We need a complete list

### Exemplification
https://github.com/eiffel-community/eiffelactory is not part of the list

### Benefits
The list of repositories are complete

### Possible Drawbacks
None

**Comment by magnusbaeck** [comment]
Missing projects are:
- [eiffelactory](https://github.com/eiffel-community/eiffelactory)
- [ml-jmespath-generator](https://github.com/eiffel-community/ml-jmespath-generator)
- [simple-event-sender](https://github.com/eiffel-community/simple-event-sender)

The ml-jmespath-generator repository only contains a LICENSE file and hasn't been touched since 2018 so I think it makes more sense to archive it.
