### ISSUE TITLE
Update the Security process

### ISSUE THREAD

**Issue by m-linner-ericsson** [eiffel-community/community#141]
### Description

We need to update the security process to include:

* Handle Dependabot alerts
* Add a description on what responsibilities maintainers have in the security process

### Motivation

Currently the process is unclear creating confusion

### Exemplification

N/A

### Benefits

Clear process

### Possible Drawbacks

None that I can think of

**Comment by k-hallen-ericsson** [comment]
Some thoughts on this. @fredjn please add to this

Dependabot
Seems like you have to be an admin for a repository to receive notifications and also have notifications enabled in your personal settings. 
Proposal: add to governance page that maintainers shall be admin/some shall be admin (?) and that they have to enable notifications. Shall we start with that it is recommended that they also act on the notifications. 
Since you need to be and admin to receive notifications it will be up to each repository maintainers to act, this will not be visible to e.g. security officers.

Responsibility for maintainers
I would also include an update for the security officers. Today the governance page says that officers shall "ensure" several things. We need to elaborate on what "ensure" means.

**Comment by magnusbaeck** [comment]
> Seems like you have to be an admin for a repository to receive notifications and also have notifications enabled in your personal settings.

Really? Judging by https://github.com/organizations/eiffel-community/settings/security_analysis

![image](https://user-images.githubusercontent.com/9032797/196439990-1701ce25-eca9-4bd0-92e2-9ee2e4ea6799.png)

this isn't true and security officers should have the necessary permissions. Also, from the settings of an random repository (https://github.com/eiffel-community/eiffel/settings/security_analysis):
![image](https://user-images.githubusercontent.com/9032797/196440563-395e236e-805b-415b-b6d1-db98338add09.png)

**Comment by e-backmark-ericsson** [comment]
@fredjn could you look into this, if it works better for you than for Kristofer? Could you ask GitHub if it does not work?

**Comment by fredjn** [comment]
I get 404 when trying to access https://github.com/eiffel-community/eiffel/settings/security_analysis and https://github.com/organizations/eiffel-community/settings/security_analysis, so something is wrong I guess.

**Comment by fredjn** [comment]
This could have something to do with it though ;)
![image](https://user-images.githubusercontent.com/4248115/199915475-0393a95d-8702-4bc6-9b5b-1aa66d7526b7.png)

**Comment by t-persson** [comment]
@k-hallen-ericsson  and @fredjn  you have both been added to the group and should now have access to security features.

**Comment by e-backmark-ericsson** [comment]
@k-hallen-ericsson , @fredjn  - do you need any more input on this from TC to progress this work?

**Comment by k-hallen-ericsson** [comment]
@e-backmark-ericsson thanks for the reminder, no we should be able to conclude this now.

**Comment by fredjn** [comment]
The motivation to this issue mentions that the current process is unclear and creates confusion. Would it be possible to elaborate a bit on this? Would be nice to have examples to go by when updating end refining the process, so we don't repeat past mistakes.

**Comment by k-hallen-ericsson** [comment]
I proposed updates for the security officer description. @fredjn will propose changes on dependabot settings for maintainers.

**Comment by k-hallen-ericsson** [comment]
@fredjn any comments? Should I propose updates for the maintainer responsibility?

**Comment by e-backmark-ericsson** [comment]
@k-hallen-ericsson , @fredjn , can this issue be closed now?
