### ISSUE TITLE
Review and propose updates to GOVERNANCE.md

### ISSUE THREAD

**Issue by ewelinawilkosz** [eiffel-community/community#44]
### Description
Too long and complicated GOVERNANCE documents may scare away potential contributor, time to have a fresh look at ours and - if need be - propose updates

### Motivation
So joining the community is an easier and  welcoming thing

### Exemplification
N/A

### Benefits
So joining the community is an easier and  welcoming thing

**Comment by fdegir** [comment]
I don't think the governance document is too long or complicated since the chapter "Community Bootstrap Process" is expected to disappear once the community settles on the governance and it is not part of the actual governance.

If you look at the rest of the document, it talks about really basic stuff which needs to be documented.
- projects: what are they and how they work
- roles: what are the roles and their responsibilities
- groups: what are the groups within the community, roles within groups, and their responsibilities

And the bootstrap chapter of the document aims to clarify these points and perhaps settle on some basic principles and processes which is already discussed under various issues/PRs such as
- list of projects, repositories owned by projects, and the maintainers for those [0][1][2]
- process related to projects such as lifecycle [3]

[0] https://github.com/eiffel-community/community/issues/6
[1] https://github.com/eiffel-community/community/issues/39
[2] https://github.com/eiffel-community/community/issues/7
[3] https://github.com/eiffel-community/eiffel-repository-template/issues/9

**Comment by k-hallen-ericsson** [comment]
Can we close this issue since we have had a community reboot with a technical committee? @ewelinawilkosz

**Comment by e-backmark-ericsson** [comment]
The COMMUNITY docs have been updated substantially since this issue was written, and are now considered to be in pretty good shape. Therefore this issue is now closed.
