### ISSUE TITLE
Add new project 'ETOS'

### ISSUE THREAD

**Issue by t-persson** [eiffel-community/community#57]
I changed the template to follow the Project Lifecycle Process.
Note that we do not need the repositories yet. We are aiming at setting up ETOS open source at the end of this month.
I can also create the repositories myself, I think. We just need approval :)

### Name
ETOS

### Description

ETOS is an abbreviation of Eiffel Test Orchestration System. It is a modern driver of test automation and it communicates using the Eiffel protocol.
It is a good entry-point in building a full-scale Eiffel solution at a company and our company is using it internally for executing test automation in a structured way.

The main selling point of ETOS is the fact that it separates the concerns of test automation in to three distinct groups. The System/Tools engineers, the test automation engineers and the testers.
System/Tools engineers make sure that the system is up and running and that all the infrastructure around ETOS is running as it should.
Test automation engineers create the recipes that define how to execute a given test or test suite.
Testers decide which recipes need to execute within the CI/CD pipeline.

Note that a person or entity may, of course, be responsible for more than one of these roles.

### Project license
ETOS will be licensed the same as every other project within the Eiffel community; under Apache 2.0.

### Name of initial maintainers
Anders Josephson <anders.josephson@axis.com>
Fredrik Fristedt <fredrik.fristedt@axis.com>
Tobias Persson <tobias.persson@axis.com>

### Infrastructure needs such as Git repositories
ETOS is a large project with many microservices.
For starters we will need these repositories:

- etos
- etos-suite-starter
- etos-suite-runner
- etos-test-runner
- etos-test-runner-containers
- etos-api
- etos-environment-provider
- etos-library
- etos-client

We have chosen the prefix "etos-" for these projects instead of "eiffel-" as it makes it clearer that it's part of the "ETOS" project.
This should be clarified in the "PROJECTS.md" file that "ETOS = Eiffel Test Orchestration System". It should also be clarified in each individual repository.

In terms of extra infrastructure we would need to publish Docker containers as well as Helm charts for these. Not sure if that should be provided by the Eiffel community or not.

**Comment by fdegir** [comment]
The proposal looks good to me so +1.

The question of Eiffel community providing the extra infrastructure that is required for the project will hopefully be clarified soon as part of the ongoing [infra discussions](https://hackmd.io/X3Nrxe4MRdSJI_lsTkSwiQ?view).

/cc @eiffel-community/eiffel-community-maintainers

**Comment by m-linner-ericsson** [comment]
+1

**Comment by fredjn** [comment]
+1

**Comment by sodero** [comment]
+1

**Comment by d-stahl-ericsson** [comment]
No objections! And no comment on the infrastructure question, as I have previously not been involved and don't have anything useful to add at this point.

As part of general community governance, should we have appointed people responsible to act on issues such as this? It's great that we're off to a good start with a bootstrap committee, but unless it's clear who is expected to actually do something I'm worried that everybody's responsibility becomes nobody's responsibility. Perhaps it's already taken care of and I'm simply ignorant.

**Comment by k-hallen-ericsson** [comment]
+1

**Comment by fdegir** [comment]
> As part of general community governance, should we have appointed people responsible to act on issues such as this?

We have such person already; generally chairs monitor TC backlog for issues such as this and maillist for TC related items and brings them to the attention of the Technical Committee.

> unless it's clear who is expected to actually do something I'm worried that everybody's responsibility becomes nobody's responsibility. Perhaps it's already taken care of and I'm simply ignorant.

You are right about your comment. Even though we stated that [_chair must ensure that the community processes are being adhered to_](https://github.com/eiffel-community/community/blob/master/GOVERNANCE.md#technical-committee-chair), we can be more explicit with the responsibilities so everyone is aware of who is doing what.

As a general rule; anything that comes in to this repo, whether it is in the form of issue or PR, is candidate for TC members to take a look at without being asked, comment and/or vote since it could be amendments to community documentation, new project proposal, or project creation and all these require engagement from TC. If the chair sees there is no progress for a given item within a reasonable timeframe, he or she needs to get TC members to act.

Regarding this specific issue; what we are doing under this issue right now is exercising [project acceptance/creation process](https://github.com/eiffel-community/community/blob/master/PROJECT_LIFECYCLE.md#project-acceptance-process) documented in project lifecycle. This process requires simple majority of the TC so the expectation from the members of TC is to monitor the community repo issues and PRs and comment/vote accordingly. 

I have added topics on the responsibilities of TC members and chair for the next meeting so we can take a discussion and clarify any question people may have. But the general rule is; communities start with the basic processes followed by other communities and adapt them to their community over time. So if we see something that doesn't work or cumbersome, we adjust.

**Comment by henning-roos** [comment]
+1

**Comment by fdegir** [comment]
If I'm not counting incorrectly, this project proposal is accepted by the votes from the majority of the TC.

Congratulations @t-persson, you got yourself a new project!

The next things to do are; create project maintainers group, create repositories, and list the project on [PROJECTS.md](https://github.com/eiffel-community/community/blob/master/PROJECTS.md#project-facts) with its facts so we make its existence visible.

**Comment by t-persson** [comment]
Perfect.
We will start with the pull requests soon.

Thank you all for reviewing this issue!

**Comment by e-backmark-ericsson** [comment]
+1, and I believe we should also create an 'etos' topic in the GitHub community, to easily group the repos into the ETOS project, similarly to e.g. REMReM: https://github.com/search?q=topic%3Aremrem+org%3Aeiffel-community+fork%3Atrue

**Comment by t-persson** [comment]
Merged
